evaluators:
  - _target_: metrics.video_evaluation.EpipolarEvaluator
    descriptor_type: sift
    sampling_rate: 1
  # - _target_: metrics.video_evaluation.DynamicsEvaluator

metadata_folder: /scratch/shared/beegfs/okupyn/WanT2VGenerations
save_folder: /scratch/shared/beegfs/okupyn/WanT2VGenerations/MetadataSIFT
save_frequency: 200
